const transactions = [
  {
    payacct_description: undefined,
    signon_id: '322205',
    srvrtid: 'a5e7c35eu9b77',
    clienttid: 'p4aiTKtTnhPms2HzdLJiXKmzSRKgEQU6',
    payeetid: null,
    banktid: 'a5e7c35eu9b77',
    payeeid: '130',
    payacct: '233557550220',
    trnamt: '1.00',
    payccy: 'GHS',
    total_amt_forex: '1.02',
    fees: '0.02',
    payccy_forex: 'GHS',
    memo: '{"serviceDescription":"","billerid":"","denomSrvrtid":"","paymentOptionSrvrtid":"7727156252","paymentOptionRef":"My expressCard","additionalData":{"Reference ":""}}',
    from_bank: '29',
    from_bank_branch: '200002',
    from_bank_account: 'ianyimiah@gmail.com',
    to_bank: '29',
    to_bank_branch: '200002',
    to_bank_account: '0200134471760602',
    status_code_id: '2000',
    timestamp: '2022-08-01 11:47:26',
    pmtprccode: 'FAILEDON',
    dtpmtprc: '2022-08-01 11:47:26',
    retry: 'FALSE',
    user_email: 'ianyimiah@gmail.com',
    rerun_count: '0',
    paid: 'TRUE',
    recurring_payment: 'FALSE',
    package: '',
    denom_srvrtid: '',
    paymentoption_srvrtid: '7727156252',
    paymentoption_ref: 'My expressCard',
    paymentoption_display_name: 'Express Card',
    paymentoption_type: 'EXPRESSCARD',
    additional_data: {
      'Reference ': {
        value: '',
      },
    },
    dis_total_amt_forex: 'GHS 1.02',
    dis_trnamt: 'GHS 1.00',
    payment_type: 'WALLET_GW',
    receipt_totalamt_display: 'GHS 1.04',
    receipt_trnamt_display: 'GHS 1.02',
    receipt_fees_display: 'GHS 0.02',
    transaction_status: 'Processing',
    merchant_service_name: 'MTN Mobile Money',
    service_account: 'MTN Mobile Money- 233557550220',
    merchant_service_srvrtid: '3243434334545',
    additionaldata_line1_type: null,
    service_account_description: 'My bro',
    payment_source: 'expressPay Rewards',
    date: '2022-08-01',
    serviceName: 'MTN Mobile Money',
    paymentOption: {
      srvrtid: '7727156252',
      name: 'EXPRESSCARD',
      display_name: 'Express Card',
      type: 'EXPRESSCARD',
      country: 'GH',
      thumbnail: 'images/icons/v2/ep_card.png',
      thumbnail_medium: 'images/icons/v2/ep_card.png',
      thumbnail_large: 'images/icons/v2/ep_card.png',
      card_bg: 'images/cards/expresscard.png',
      timestamp: '2017-01-11 17:31:58',
      active: 'TRUE',
      rank: '1',
      enable_receive: 'TRUE',
      enable_send: 'TRUE',
      merchantservice_srvrtid_receive: null,
      supports_scheduled_payments: 'TRUE',
    },
  },
  {
    signon_id: '320320',
    srvrtid: '1ae4fd39ud6de',
    clienttid: 'wkIrjZAKigFUEmCLGOxoGbyJ0R3MXpoy',
    payeetid: null,
    banktid: '1ae4fd39ud6de',
    payeeid: '79',
    payacct: '233247350398',
    trnamt: '0.10',
    payccy: 'GHS',
    total_amt_forex: '0.10',
    fees: '0.00',
    payccy_forex: 'GHS',
    memo: '{"serviceDescription":":__TOPUP__","billerid":"","denomSrvrtid":"7564535465676","paymentOptionSrvrtid":"7727156252","paymentOptionRef":"My expressCard","additionalData":{"MEMO":""}}',
    from_bank: '29',
    from_bank_branch: '200002',
    from_bank_account: 'ianyimiah@gmail.com',
    to_bank: '29',
    to_bank_branch: '200002',
    to_bank_account: '0200134471760602',
    status_code_id: '2012',
    timestamp: '2022-07-14 20:01:38',
    pmtprccode: 'FAILEDON',
    dtpmtprc: '2022-07-14 20:01:38',
    retry: 'FALSE',
    user_email: 'ianyimiah@gmail.com',
    rerun_count: '0',
    paid: 'TRUE',
    recurring_payment: 'FALSE',
    package: 'Dev Package',
    denom_srvrtid: '7564535465676',
    paymentoption_srvrtid: '7727156252',
    paymentoption_ref: 'My expressCard',
    paymentoption_display_name: 'Express Card',
    paymentoption_type: 'EXPRESSCARD',
    additional_data: {
      MEMO: {
        value: '',
      },
    },
    dis_total_amt_forex: 'GHS 0.10',
    dis_trnamt: 'GHS 0.10',
    payment_type: 'WALLET_GW',
    receipt_totalamt_display: 'GHS 0.10',
    receipt_trnamt_display: 'GHS 0.10',
    receipt_fees_display: 'GHS 0.00',
    transaction_status: 'Processing',
    merchant_service_name: 'MTN Prepaid',
    service_account: 'MTN Prepaid- 233247350398',
    merchant_service_srvrtid: '4695524396170',
    additionaldata_line1_type: null,
    service_account_description: 'Nana',
    payment_source: 'expressPay Rewards',
    date: '2022-07-14',
    serviceName: 'MTN Prepaid',
    paymentOption: {
      srvrtid: '7727156252',
      name: 'EXPRESSCARD',
      display_name: 'Express Card',
      type: 'EXPRESSCARD',
      country: 'GH',
      thumbnail: 'images/icons/v2/ep_card.png',
      thumbnail_medium: 'images/icons/v2/ep_card.png',
      thumbnail_large: 'images/icons/v2/ep_card.png',
      card_bg: 'images/cards/expresscard.png',
      timestamp: '2017-01-11 17:31:58',
      active: 'TRUE',
      rank: '1',
      enable_receive: 'TRUE',
      enable_send: 'TRUE',
      merchantservice_srvrtid_receive: null,
      supports_scheduled_payments: 'TRUE',
    },
  },
  {
    signon_id: '320008',
    srvrtid: '6780cc3au9e7d',
    clienttid: '0kUQ3GUnH6tBTOB7k5yNueFd79P4ANjK',
    payeetid: null,
    banktid: '6780cc3au9e7d',
    payeeid: '78',
    payacct: '233504116920',
    trnamt: '1.00',
    payccy: 'GHS',
    total_amt_forex: '1.00',
    fees: '0.00',
    payccy_forex: 'GHS',
    memo: '{"serviceDescription":"Dev Package","billerid":"","denomSrvrtid":"83277328323335","paymentOptionSrvrtid":"4343121293","paymentOptionRef":"233504116920"}',
    from_bank: '28',
    from_bank_branch: '100001',
    from_bank_account: 'ianyimiah@gmail.com',
    to_bank: '26',
    to_bank_branch: '120108',
    to_bank_account: '6011206506',
    status_code_id: '2000',
    timestamp: '2022-07-13 12:05:45',
    pmtprccode: 'FAILEDON',
    dtpmtprc: '2022-07-13 12:05:45',
    retry: 'FALSE',
    user_email: 'ianyimiah@gmail.com',
    rerun_count: '0',
    paid: 'FALSE',
    recurring_payment: 'FALSE',
    package: 'Dev Package',
    denom_srvrtid: '83277328323335',
    paymentoption_srvrtid: '4343121293',
    paymentoption_ref: '233504116920',
    paymentoption_display_name: 'Vodafone Cash',
    paymentoption_type: 'MOBILEMONEY',
    dis_total_amt_forex: 'GHS 1.00',
    dis_trnamt: 'GHS 1.00',
    payment_type: 'VODAFONE_MM_GW',
    receipt_totalamt_display: 'GHS 1.00',
    receipt_trnamt_display: 'GHS 1.00',
    receipt_fees_display: 'GHS 0.00',
    transaction_status: 'Failed',
    merchant_service_name: 'Vodafone Prepaid Topup',
    service_account: 'Vodafone Prepaid Topup- 233504116920',
    merchant_service_srvrtid: '8938597866600',
    additionaldata_line1_type: null,
    service_account_description: 'nana',
    payment_source: 'expressPay Processing',
    date: '2022-07-13',
    serviceName: 'Vodafone Prepaid Topup',
    paymentOption: {
      srvrtid: '4343121293',
      name: 'VODAMM',
      display_name: 'Vodafone Cash',
      type: 'MOBILEMONEY',
      country: 'GH',
      thumbnail: 'images/icons/v2/vodafone_card.png',
      thumbnail_medium: 'images/icons/v2/vodafone_card.png',
      thumbnail_large: 'images/icons/v2/vodafone_sim.png',
      card_bg: 'images/cards/vodafonemm.png',
      timestamp: '2017-01-11 17:31:58',
      active: 'TRUE',
      rank: '3',
      enable_receive: 'FALSE',
      enable_send: 'TRUE',
      merchantservice_srvrtid_receive: null,
      supports_scheduled_payments: 'FALSE',
    },
  },
];

function rowsToCsStr(rows: string[][]) {
  const rowsArr = [];
  for (const row of rows) {
    rowsArr.push(row.join(','));
  }

  return rowsArr.join('\n');
}

function constructCsv(headings: string[], rows: string[][]) {
  let csv = `${headings.join(',')}\n${rowsToCsStr(rows)}`;
  return csv;
}

function transactionsToCsv() {
  const headings = [
    '"Date"',
    '"Account"',
    '"Amount"',
    '"Fee"',
    '"Payment Method"',
    '"Transaction ID"',
    '"Reference"',
    '"Status"',
  ];

  const rows = transactions.map((transaction) => {
    const additionalData = transaction.additional_data;
    let referenceObj = additionalData
      ? additionalData['Reference '] ?? additionalData['MEMO']
      : { value: '' };

    return [
      `"${transaction.date}"`,
      `"${transaction?.payacct_description || transaction.payacct} | ${
        transaction.serviceName
      }"`,
      `"${transaction.payccy}${transaction.trnamt}"`,
      `"${transaction.payccy}${transaction.fees}"`,
      `"${transaction.paymentoption_ref}"`,
      `"${transaction.srvrtid}"`,
      `"${referenceObj.value ?? '-'}"`,
      `${transaction.transaction_status}`,
    ];
  });

  return constructCsv(headings, rows);
}

console.log(transactionsToCsv());
